
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PopulationDB", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://10.136.4.18:92/PopulationDB.asmx?wsdl")
public class PopulationDB
    extends Service
{

    private final static URL POPULATIONDB_WSDL_LOCATION;
    private final static WebServiceException POPULATIONDB_EXCEPTION;
    private final static QName POPULATIONDB_QNAME = new QName("http://tempuri.org/", "PopulationDB");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.136.4.18:92/PopulationDB.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POPULATIONDB_WSDL_LOCATION = url;
        POPULATIONDB_EXCEPTION = e;
    }

    public PopulationDB() {
        super(__getWsdlLocation(), POPULATIONDB_QNAME);
    }

    public PopulationDB(WebServiceFeature... features) {
        super(__getWsdlLocation(), POPULATIONDB_QNAME, features);
    }

    public PopulationDB(URL wsdlLocation) {
        super(wsdlLocation, POPULATIONDB_QNAME);
    }

    public PopulationDB(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POPULATIONDB_QNAME, features);
    }

    public PopulationDB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PopulationDB(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PopulationDBSoap
     */
    @WebEndpoint(name = "PopulationDBSoap")
    public PopulationDBSoap getPopulationDBSoap() {
        return super.getPort(new QName("http://tempuri.org/", "PopulationDBSoap"), PopulationDBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PopulationDBSoap
     */
    @WebEndpoint(name = "PopulationDBSoap")
    public PopulationDBSoap getPopulationDBSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PopulationDBSoap"), PopulationDBSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PopulationDBSoap
     */
    @WebEndpoint(name = "PopulationDBSoap12")
    public PopulationDBSoap getPopulationDBSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "PopulationDBSoap12"), PopulationDBSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PopulationDBSoap
     */
    @WebEndpoint(name = "PopulationDBSoap12")
    public PopulationDBSoap getPopulationDBSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "PopulationDBSoap12"), PopulationDBSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POPULATIONDB_EXCEPTION!= null) {
            throw POPULATIONDB_EXCEPTION;
        }
        return POPULATIONDB_WSDL_LOCATION;
    }

}
