
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PopulationDBSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PopulationDBSoap {


    /**
     * �����˿ڿ�ӿ�
     * 
     * @param machineID
     * @param idCardNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AppInforCheckForJiangXi", action = "http://tempuri.org/AppInforCheckForJiangXi")
    @WebResult(name = "AppInforCheckForJiangXiResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AppInforCheckForJiangXi", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AppInforCheckForJiangXi")
    @ResponseWrapper(localName = "AppInforCheckForJiangXiResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AppInforCheckForJiangXiResponse")
    public String appInforCheckForJiangXi(
        @WebParam(name = "idCardNum", targetNamespace = "http://tempuri.org/")
        String idCardNum,
        @WebParam(name = "machineID", targetNamespace = "http://tempuri.org/")
        String machineID);

}
